[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
listen.owner = www-data
listen.group = www-data

pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
pm.max_requests = 300

clear_env = no
catch_workers_output = yes
