#!/usr/bin/env python3
"""publish.py build | dry | apply | verify      (always run from the project root)
build [N ...]  collects the articles that check_new.py marks ok, that have an independent
        check (research/<task_id>/audit.md) and that are not yet published, into
        pipeline/release/<stamp>/ (manifest.jsonl, publish.sh, rollback.sql).
        With topic numbers, only those. Rewrites of live posts (replaces_post) are
        skipped; they go live with update_live.py.
dry     runs the inserts on the LIVE database inside a transaction and rolls it back.
        Nothing is kept except that the id counter moves forward.
apply   backs up the posts table on the VPS, inserts, commits, compares hashes and
        records the new ids in pipeline/published.jsonl. Needs a clean dry run first.
verify  opens each published post on the live site and checks that it renders.
New rows: creatorname 'Anupam K', image 'default.png', cleansed 1, wikilink NULL."""
import sys,os,re,json,glob,time,hashlib,subprocess,gzip,urllib.parse
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__))); from common import *
SSH=['gcloud','compute','ssh','crimewiki','--zone','us-east1-c','--command']
CATS={'Crimes','Criminals','Groups'}
def hx(s): return "CONVERT(X'"+s.encode('utf-8').hex()+"' USING utf8mb4)"
def published():
    p=f'{BASE}/published.jsonl'
    return [json.loads(l) for l in open(p,encoding='utf-8') if l.strip()] if os.path.exists(p) else []
def latest():
    d=sorted(glob.glob(f'{BASE}/release/2*')); return d[-1] if d else sys.exit('no release; run: publish.py build')
def live_titles():
    f=sorted(glob.glob('tmp/live-snapshot/posts-*.tsv.gz'))[-1]
    return {l.split('\t')[1].strip().lower() for l in gzip.open(f,'rt',encoding='utf-8')}

def build():
    subprocess.run([sys.executable,f'{BASE}/check_new.py'],stdout=subprocess.DEVNULL)
    state=json.load(open(f'{BASE}/check-state.json')); T=topics(); done={p['task_id'] for p in published()}; taken=live_titles()|{p['title'].lower() for p in published()}
    want={tid(n) for n in sys.argv[2:]}
    stamp=time.strftime('%Y%m%d-%H%M%S'); d=f'{BASE}/release/{stamp}'; rows=[]; now=int(time.time())
    for t in sorted(state):
        s=state[t]; meta=T[t]
        if t in done: continue
        if want and t not in want: continue
        if meta.get('replaces_post'): print('SKIP rewrite of live post',meta['replaces_post'],'(update_live.py)',t,meta['title']); continue
        if not os.path.exists(f'{BASE}/research/{t}/audit.md'): print('SKIP no independent check (no audit.md)',t,meta['title']); continue
        if not s['ok']: print('SKIP not ok   ',t,meta['title']); continue
        title=meta['title'].strip(); cat=meta['category']; country=(meta.get('country') or '').strip()
        if title.lower() in taken or '/' in title or '?' in title or len(title)>200 or cat not in CATS or len(country)>50:
            print('SKIP bad title/category (duplicate, "/", "?" or unknown category)',t,title); continue
        content=article(t).strip()
        rows.append(dict(task_id=t,title=title,category=cat,country=country,datetime=str(now+len(rows)),sha256=hashlib.sha256(content.encode('utf-8')).hexdigest(),chars=len(content),words=s['words'],content=content))
    if not rows: sys.exit('nothing to publish')
    os.makedirs(d)
    sql=["SET NAMES utf8mb4;","START TRANSACTION;","SET @before = (SELECT MAX(id) FROM posts);","SELECT 'BEFORE', COUNT(*), MAX(id) FROM posts;"]
    for r in rows:
        sql.append("INSERT INTO posts (datetime, title, wikilink, titlerepeat, creatorname, country, image, content, categoryname, cleansed) "
            f"SELECT '{r['datetime']}', {hx(r['title'])}, NULL, NULL, 'Anupam K', {hx(r['country']) if r['country'] else 'NULL'}, 'default.png', {hx(r['content'])}, '{r['category']}', 1 "
            f"FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM posts WHERE title = {hx(r['title'])} COLLATE utf8mb4_unicode_ci);")
    sql.append("SELECT 'NEW', id, title, CHAR_LENGTH(content), SHA2(content,256) FROM posts WHERE id > @before ORDER BY id;")
    sh=f'''# Generated by pipeline/publish.py. "dry" rolls back; "apply" backs up, then commits.
set -u
MODE="${{1:-dry}}"
DB=$(sudo docker ps --format "{{{{.Names}}}}" </dev/null | grep -i -E "db|mysql" | grep -v -i phpmyadmin | head -1)
[ -n "$DB" ] || {{ echo "ERROR no database container"; exit 1; }}
if [ "$MODE" = "apply" ]; then
  mkdir -p "$HOME/crimewiki-backups"
  find "$HOME/crimewiki-backups" -name 'posts-before-*.sql.gz' -size -2k -delete
  B="$HOME/crimewiki-backups/posts-before-{stamp}.sql.gz"
  sudo docker exec "$DB" sh -c 'mysqldump --skip-lock-tables --no-tablespaces --default-character-set=utf8mb4 -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" posts 2>/dev/null' </dev/null | gzip -c > "$B"
  SIZE=$(stat -c %s "$B")
  echo "BACKUP $B $SIZE"
  [ "$SIZE" -gt 1000000 ] || {{ rm -f "$B"; echo "ERROR backup too small; nothing was inserted"; exit 1; }}
  END="COMMIT;"
else
  END="ROLLBACK;"
fi
{{ cat <<'SQLEOF'
{chr(10).join(sql)}
SQLEOF
echo "$END"
echo "SELECT 'AFTER', COUNT(*), MAX(id) FROM posts;"
}} | sudo docker exec -i "$DB" sh -c 'mysql --default-character-set=utf8mb4 -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" -B -N 2>&1' | grep -v "Using a password"
echo "MODE $MODE DONE"
'''
    open(f'{d}/publish.sh','w',encoding='utf-8').write(sh)
    with open(f'{d}/manifest.jsonl','w',encoding='utf-8') as f:
        for r in rows: f.write(json.dumps({k:v for k,v in r.items() if k!='content'},ensure_ascii=False)+'\n')
    print(f'release {d}: {len(rows)} new posts')
    for r in rows: print('  ',r['task_id'],'|',r['category'],'|',r['words'],'words |',r['title'])
    print('next: python3 pipeline/publish.py dry')

def run(mode):
    d=latest(); man=[json.loads(l) for l in open(f'{d}/manifest.jsonl',encoding='utf-8')]
    if mode=='apply':
        if not os.path.exists(f'{d}/dry.ok'): sys.exit('run a clean dry run first: publish.py dry')
        if os.path.exists(f'{d}/apply.out'): sys.exit('this release was already applied')
    r=subprocess.run(SSH+[f'bash -s -- {mode}'],stdin=open(f'{d}/publish.sh','rb'),capture_output=True,text=True)
    out=r.stdout; open(f'{d}/{mode}.out','w',encoding='utf-8').write(out+'\n--- stderr\n'+r.stderr)
    new=[l.split('\t') for l in out.splitlines() if l.startswith('NEW\t')]
    for l in out.splitlines():
        if l.startswith(('BEFORE','AFTER','BACKUP','ERROR','MODE')) or 'ERROR' in l: print(l[:200])
    got={n[2]:n for n in new}; okall=len(new)==len(man) and 'ERROR' not in out and f'MODE {mode} DONE' in out
    for m in man:
        n=got.get(m['title']); good=bool(n) and n[4]==m['sha256']; okall&=good
        print(f"  {'ok ' if good else 'BAD'} id {n[1] if n else '-':>5} | {m['title']}")
    if not okall:
        os.replace(f'{d}/{mode}.out',f'{d}/{mode}.failed.out')
        sys.exit(f'{mode.upper()} FAILED; see {d}/{mode}.failed.out. Nothing was recorded.')
    if mode=='dry':
        open(f'{d}/dry.ok','w').write('ok'); print(f'DRY RUN OK: {len(man)} posts would be inserted. Rolled back. next: publish.py apply')
    else:
        with open(f'{BASE}/published.jsonl','a',encoding='utf-8') as f:
            for m in man: f.write(json.dumps(dict(task_id=m['task_id'],id=int(got[m['title']][1]),title=m['title'],sha256=m['sha256'],release=os.path.basename(d)),ensure_ascii=False)+'\n')
        ids=','.join(got[m['title']][1] for m in man)
        open(f'{d}/rollback.sql','w').write(f"-- Removes this release. Run only if the owner asks.\nDELETE FROM posts WHERE id IN ({ids}) AND creatorname='Anupam K' AND id > 1140;\n")
        print(f'APPLIED: {len(man)} posts are live. Ids {ids}. next: publish.py verify')

def slug(title):
    # same rule as post_slug() in include/functions.php
    t=re.sub("['\u2019\u2018\u02bc`\u00b4]",'',title.lower())
    return re.sub(r'[\W_]+','-',t).strip('-')

def verify():
    bad=0
    for p in published():
        url='https://crimewiki.site/post/'+urllib.parse.quote(slug(p['title']),safe='')
        r=subprocess.run(['curl','-sL','--max-time','30','-w','\n%{http_code}',url],capture_output=True,text=True)
        code=r.stdout.rsplit('\n',1)[-1]; good=code=='200' and '<h2>Introduction</h2>' in r.stdout; bad+=not good
        print('ok ' if good else 'BAD',code,url)
    print('all live' if not bad else f'{bad} posts did not render')

a=sys.argv[1] if len(sys.argv)>1 else ''
build() if a=='build' else run(a) if a in('dry','apply') else verify() if a=='verify' else print(__doc__)
