#!/usr/bin/env python3
"""update_live.py build [N ...] | dry | apply | verify      (always run from the project root)
Replaces the text of existing live posts with checked rewrites (topics with "replaces_post").
Only the content column changes; id, title, URL, image and category stay as they are.
build   collects rewrites that check_new.py marks ok, that have an independent check
        (research/<task_id>/audit.md) and that are not yet in updated.jsonl, into
        pipeline/update/<stamp>/ (manifest.jsonl, update.sh). With numbers, only those.
dry     runs the updates on the LIVE database inside a transaction and rolls it back.
apply   backs up the posts table on the VPS, saves each post's old text locally
        (rollback.sql), updates, commits, compares hashes, records updated.jsonl.
        Needs a clean dry run first.
verify  opens each updated post on the live site and checks that the new text renders."""
import sys,os,re,json,glob,time,hashlib,subprocess,urllib.parse
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__))); from common import *
SSH=['gcloud','compute','ssh','crimewiki','--zone','us-east1-c','--command']
def hx(s): return "CONVERT(X'"+s.encode('utf-8').hex()+"' USING utf8mb4)"
def updated():
    p=f'{BASE}/updated.jsonl'
    return [json.loads(l) for l in open(p,encoding='utf-8') if l.strip()] if os.path.exists(p) else []
def latest():
    d=sorted(glob.glob(f'{BASE}/update/2*')); return d[-1] if d else sys.exit('no update; run: update_live.py build')

def build():
    subprocess.run([sys.executable,f'{BASE}/check_new.py'],stdout=subprocess.DEVNULL)
    state=json.load(open(f'{BASE}/check-state.json')); T=topics(); done={u['task_id'] for u in updated()}
    want={tid(n) for n in sys.argv[2:]}; rows=[]
    for t in sorted(state):
        meta=T[t]; pid=meta.get('replaces_post')
        if not pid or t in done or (want and t not in want): continue
        if not state[t]['ok']: print('SKIP not ok',t,meta['title']); continue
        if not os.path.exists(f'{BASE}/research/{t}/audit.md'): print('SKIP no independent check (no audit.md)',t,meta['title']); continue
        content=article(t).strip()
        rows.append(dict(task_id=t,id=int(pid),title=meta['title'].strip(),sha256=hashlib.sha256(content.encode('utf-8')).hexdigest(),words=state[t]['words'],content=content))
    if not rows: sys.exit('nothing to update')
    stamp=time.strftime('%Y%m%d-%H%M%S'); d=f'{BASE}/update/{stamp}'; os.makedirs(d)
    ids=','.join(str(r['id']) for r in rows)
    sql=["SET NAMES utf8mb4;","START TRANSACTION;",
         f"SELECT 'OLD', id, title, CHAR_LENGTH(content), HEX(content) FROM posts WHERE id IN ({ids}) ORDER BY id;"]
    for r in rows:  # the title must match too, so a wrong id changes nothing
        sql.append(f"UPDATE posts SET content = {hx(r['content'])} WHERE id = {r['id']} AND title = {hx(r['title'])} COLLATE utf8mb4_unicode_ci;")
    sql.append(f"SELECT 'NEW', id, title, CHAR_LENGTH(content), SHA2(content,256) FROM posts WHERE id IN ({ids}) ORDER BY id;")
    sh=f'''# Generated by pipeline/update_live.py. "dry" rolls back; "apply" backs up, then commits.
set -u
MODE="${{1:-dry}}"
DB=$(sudo docker ps --format "{{{{.Names}}}}" </dev/null | grep -i -E "db|mysql" | grep -v -i phpmyadmin | head -1)
[ -n "$DB" ] || {{ echo "ERROR no database container"; exit 1; }}
if [ "$MODE" = "apply" ]; then
  mkdir -p "$HOME/crimewiki-backups"
  B="$HOME/crimewiki-backups/posts-before-update-{stamp}.sql.gz"
  sudo docker exec "$DB" sh -c 'mysqldump --skip-lock-tables --no-tablespaces --default-character-set=utf8mb4 -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" posts 2>/dev/null' </dev/null | gzip -c > "$B"
  SIZE=$(stat -c %s "$B")
  echo "BACKUP $B $SIZE"
  [ "$SIZE" -gt 1000000 ] || {{ rm -f "$B"; echo "ERROR backup too small; nothing was updated"; exit 1; }}
  END="COMMIT;"
else
  END="ROLLBACK;"
fi
{{ cat <<'SQLEOF'
{chr(10).join(sql)}
SQLEOF
echo "$END"
}} | sudo docker exec -i "$DB" sh -c 'mysql --default-character-set=utf8mb4 -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" -B -N 2>&1' | grep -v "Using a password"
echo "MODE $MODE DONE"
'''
    open(f'{d}/update.sh','w',encoding='utf-8').write(sh)
    with open(f'{d}/manifest.jsonl','w',encoding='utf-8') as f:
        for r in rows: f.write(json.dumps({k:v for k,v in r.items() if k!='content'},ensure_ascii=False)+'\n')
    print(f'update {d}: {len(rows)} live posts to replace')
    for r in rows: print('  ',r['task_id'],'| post',r['id'],'|',r['words'],'words |',r['title'])
    print('next: python3 pipeline/update_live.py dry')

def run(mode):
    d=latest(); man=[json.loads(l) for l in open(f'{d}/manifest.jsonl',encoding='utf-8')]
    if mode=='apply':
        if not os.path.exists(f'{d}/dry.ok'): sys.exit('run a clean dry run first: update_live.py dry')
        if os.path.exists(f'{d}/apply.out'): sys.exit('this update was already applied')
    r=subprocess.run(SSH+[f'bash -s -- {mode}'],stdin=open(f'{d}/update.sh','rb'),capture_output=True,text=True)
    out=r.stdout; open(f'{d}/{mode}.out','w',encoding='utf-8').write(out+'\n--- stderr\n'+r.stderr)
    old={l.split('\t')[1]:l.split('\t') for l in out.splitlines() if l.startswith('OLD\t')}
    new={l.split('\t')[1]:l.split('\t') for l in out.splitlines() if l.startswith('NEW\t')}
    for l in out.splitlines():
        if l.startswith(('BACKUP','ERROR','MODE')) or 'ERROR' in l: print(l[:200])
    okall='ERROR' not in out and f'MODE {mode} DONE' in out
    for m in man:
        o=old.get(str(m['id'])); n=new.get(str(m['id']))
        good=bool(o) and bool(n) and o[2]==m['title'] and n[4]==m['sha256']; okall&=good
        print(f"  {'ok ' if good else 'BAD'} post {m['id']:>5} | old {o[3] if o else '-'} chars -> new {n[3] if n else '-'} | {m['title']}")
    if not okall:
        os.replace(f'{d}/{mode}.out',f'{d}/{mode}.failed.out')
        sys.exit(f'{mode.upper()} FAILED; see {d}/{mode}.failed.out. Nothing was recorded.')
    if mode=='dry':
        open(f'{d}/dry.ok','w').write('ok'); print(f'DRY RUN OK: {len(man)} posts would be replaced. Rolled back. next: update_live.py apply')
        return
    with open(f'{d}/rollback.sql','w',encoding='utf-8') as f:
        f.write('-- Puts back the old text of these posts. Run only if the owner asks.\nSET NAMES utf8mb4;\n')
        for m in man: f.write(f"UPDATE posts SET content = CONVERT(X'{old[str(m['id'])][4]}' USING utf8mb4) WHERE id = {m['id']};\n")
    with open(f'{BASE}/updated.jsonl','a',encoding='utf-8') as f:
        for m in man: f.write(json.dumps(dict(task_id=m['task_id'],id=m['id'],title=m['title'],sha256=m['sha256'],old_chars=int(old[str(m['id'])][3]),update=os.path.basename(d)),ensure_ascii=False)+'\n')
    print(f'APPLIED: {len(man)} posts replaced. Old text saved in {d}/rollback.sql. next: update_live.py verify')

def slug(title):
    # same rule as post_slug() in include/functions.php
    t=re.sub("['’‘ʼ`´]",'',title.lower())
    return re.sub(r'[\W_]+','-',t).strip('-')

def verify():
    bad=0
    for u in updated():
        heads=re.findall(r'<h2>(.*?)</h2>',article(u['task_id']))
        mark=heads[1] if len(heads)>1 else 'Introduction'
        url='https://crimewiki.site/post/'+urllib.parse.quote(slug(u['title']),safe='')
        r=subprocess.run(['curl','-sL','--max-time','30','-w','\n%{http_code}',url],capture_output=True,text=True)
        code=r.stdout.rsplit('\n',1)[-1]; good=code=='200' and f'<h2>{mark}</h2>' in r.stdout; bad+=not good
        print('ok ' if good else 'BAD',code,url,'| heading:',mark)
    print('all updated posts show the new text' if not bad else f'{bad} posts did not show the new text')

a=sys.argv[1] if len(sys.argv)>1 else ''
build() if a=='build' else run(a) if a in('dry','apply') else verify() if a=='verify' else print(__doc__)
