# Reverse proxy (maintenance mode)
server {
  listen 80;
  server_name __DOMAIN__ __DOMAIN_WWW__;

  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name __DOMAIN__ __DOMAIN_WWW__;

  ssl_certificate     /etc/letsencrypt/live/__DOMAIN__/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/__DOMAIN__/privkey.pem;

  location / {
    root /var/www/maintenance;
    try_files /index.html =503;
  }

  error_page 503 /index.html;
}
