ProxyRequests Off
ProxyPreserveHost On

ProxyPass /phpmyadmin/ http://phpmyadmin:80/
ProxyPassReverse /phpmyadmin/ http://phpmyadmin:80/
ProxyPass /phpmyadmin http://phpmyadmin:80/
ProxyPassReverse /phpmyadmin http://phpmyadmin:80/
